spring:
  application:
    name: kanban
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5438/kanban
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml